version: '3.7'
services:
  tf_serving:
    image: 162.55.189.72:5000/tf_model
    deploy:
      replicas: 2
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    image: 162.55.189.72:5000/gateway
    deploy:
      replicas: 2
    build: gateway/
    ports:
      - 14005:14005
    volumes:
      - /root/final/indices:/indices
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_0:
    image: 162.55.189.72:5000/index_service
    deploy:
      replicas: 2
    build: index_service/
    ports:
      - 14000:14000
    volumes:
      - /root/final/indices:/indices
    environment:
      - CLUSTER_ID=0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_1:
    image: 162.55.189.72:5000/index_service
    deploy:
      replicas: 2
    build: index_service/
    ports:
      - 14001:14000
    volumes:
      - /root/final/indices:/indices
    environment:
      - CLUSTER_ID=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_2:
    image: 162.55.189.72:5000/index_service
    deploy:
      replicas: 2
    build: index_service/
    ports:
      - 14002:14000
    volumes:
      - /root/final/indices:/indices
    environment:
      - CLUSTER_ID=2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  index_service_3:
    image: 162.55.189.72:5000/index_service
    deploy:
      replicas: 2
    build: index_service/
    ports:
      - 14003:14000
    volumes:
      - /root/final/indices:/indices
    environment:
      - CLUSTER_ID=3
    extra_hosts:
      - "host.docker.internal:host-gateway"